language: android
sudo: required
jdk:
  - oraclejdk8
branches:
  only:
    - master
env:
  global:
    - ANDROID_API_LEVEL=29
    - ANDROID_EMULATOR_LEVEL=24
    - ANDROID_BUILD_TOOLS_VERSION=27.0.3
    - ADB_INSTALL_TIMEOUT=20
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL
    - android-$ANDROID_EMULATOR_LEVEL

    # Additional components
    - extra-android-m2repository
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-$ANDROID_EMULATOR_LEVEL

# Creates, starts and waits for emulator, then launch tests
script:
  - echo no | android create avd --force -n test -t "android-"$ANDROID_EMULATOR_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-window &
  - chmod +x ./ci/wait-for-emulator
  - ./ci/wait-for-emulator
  - adb shell input keyevent 82 &
  - ./gradlew connectedMockDebugAndroidTest -PdisablePreDex --continue --stacktrace
#Builds and publish the apk to the play store
after_success:
  - ./gradlew publishApkRealRelease
after_failure:
  - cat $TRAVIS_BUILD_DIR/app/build/reports/lint-results.xml
